apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: project
spec:
  schedule: "0 0 * * *"  # Every day at midnight (once per 24 hours)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: postgres-backup:latest
              env:
                - name: POSTGRES_HOST
                  value: "postgres-project"
                - name: POSTGRES_PORT
                  value: "5432"
                - name: POSTGRES_DB
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_DB
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
                - name: GCS_BUCKET
                  value: "k8s-course-project-backups"
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/key.json
              volumeMounts:
                - name: gcs-key
                  mountPath: /var/secrets/google
                  readOnly: true
          volumes:
            - name: gcs-key
              secret:
                secretName: gcs-backup-sa
          restartPolicy: OnFailure

