apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dummysite-controller-binding
subjects:
  - kind: ServiceAccount
    name: dummysite-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: dummysite-controller-role
  apiGroup: rbac.authorization.k8s.io

