apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummysite-controller-role
rules:
  - apiGroups: ["example.com"]
    resources: ["dummysites"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["example.com"]
    resources: ["dummysites/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
