steps:
  # Build the-project image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/the-project:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/the-project:latest', './the-project']
    id: 'build-the-project'

  # Build todo-backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/todo-backend:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/todo-backend:latest', './todo-backend']
    id: 'build-todo-backend'

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/the-project']
    waitFor: ['build-the-project']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/todo-backend']
    waitFor: ['build-todo-backend']

  # Set up kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --zone=${_CLUSTER_ZONE}
        kubectl kustomize ./the-project/overlays/gke | \
          sed "s|akiracry/the-project:.*|gcr.io/$PROJECT_ID/the-project:$SHORT_SHA|g" | \
          sed "s|akiracry/todo-backend:.*|gcr.io/$PROJECT_ID/todo-backend:$SHORT_SHA|g" | \
          kubectl apply -f -
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

images:
  - 'gcr.io/$PROJECT_ID/the-project:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/the-project:latest'
  - 'gcr.io/$PROJECT_ID/todo-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/todo-backend:latest'

substitutions:
  _CLUSTER_NAME: 'your-cluster-name'
  _CLUSTER_ZONE: 'europe-west1-b'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
