apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: exercises-gateway
  namespace: exercises
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80

